# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build

on:
  push:
    branches:
      - "master"
    paths:
      - "*.json"
      - "raw/**"
      - ".github/workflows/build.yml"
      - ".scripts/build.py"
  pull_request:
    branches:
      - "master"
    paths:
      - "*.json"
      - "raw/**"
      - ".github/workflows/build.yml"
      - ".scripts/build.py"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Build
      run: |
        python .scripts/build.py
    - name: Commit
      run: |
        if git diff --quiet --exit-code;
        then
          echo "Nothing to commit."
        else
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-generate json files by Github Actions"
          git push
        fi
